version: '3.8'

services:
  # Local PostgreSQL removed. Keep docker-compose small for BFF local dev.
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - REMOTE_BACKEND_URL=${REMOTE_BACKEND_URL:-http://host.docker.internal:4000}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
