version: '3.8'

services:
  # Postgres/pgadmin removed — this BFF does not require a local database.
  # Add any local dependencies you still need (e.g., redis) or keep this file minimal.

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
